---
  - name: Install EPEL Repo
    yum: name=epel-release state=installed

  - name: Install NTPD Service
    yum: name=ntp state=installed

  - name: Start and enable NTP
    service: name=ntpd  state=started  enabled=yes

  - name: Install nginx
    yum: name=nginx state=installed
    
  - name: Start & Enable nginx
    service: name=nginx state=started enabled=yes

  - name: Copy nginx configuration
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    when: inventory_hostname != 'hp'
    notify: Restart nginx   

  - name: Copy nginx configuration for wordpress
    template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
    when: inventory_hostname != 'hp'
    notify: Restart nginx
    
