---

- name: Install HAProxy
  yum: name=haproxy state=present
  tags: haproxy

- name: Add haproxy config
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart HAProxy

- name: Start & enable haproxy
  service: name=haproxy enabled=yes state=started