---
- name: web1
  group: "[webnodes]"
  memory: 512
  ip: 172.28.128.3

- name: web2
  group: "[webnodes]"
  memory: 512
  ip: 172.28.128.4

- name: web3
  group: "[webnodes]"
  memory: 512
  ip: 172.28.128.5

- name: hp
  group: "[haproxy]"
  memory: 1024
  ip: 172.28.128.6

- name: db1
  group: "[dbs]"
  memory: 1024
  ip: 172.28.128.7
