---
- name: web1
  group: "[webnodes]"
  memory: 512
  ip: 172.28.128.3
  private_key: /home/vagrant/.vagrant.d/private_key

- name: web2
  group: "[webnodes]"
  memory: 512
  ip: 172.28.128.4
  private_key: /home/vagrant/.vagrant.d/private_key

- name: web3
  group: "[webnodes]"
  memory: 512
  ip: 172.28.128.5
  private_key: /home/vagrant/.vagrant.d/private_key

- name: hp
  group: "[haproxy]"
  memory: 1024
  ip: 172.28.128.6
  private_key: /home/vagrant/.vagrant.d/private_key

- name: db1
  group: "[dbs]"
  memory: 1024
  ip: 172.28.128.7
  private_key: /home/vagrant/.vagrant.d/private_key
