---
- name: web1
  group: "[webnodes]"
  memory: 512
  ip: 192.168.12.11
  private_key: /home/vagrant/.vagrant.d/private_key

- name: web2
  group: "[webnodes]"
  memory: 512
  ip: 192.168.12.12
  private_key: /home/vagrant/.vagrant.d/private_key

- name: web3
  group: "[webnodes]"
  memory: 512
  ip: 192.168.12.13
  private_key: /home/vagrant/.vagrant.d/private_key

- name: haproxy
  group: "[haproxy]"
  memory: 1024
  ip: 192.168.12.14
  private_key: /home/vagrant/.vagrant.d/private_key
