---
  - name: Install EPEL Repo
    yum: name=epel-release state=installed

  - name: Install NTPD Service
    yum: name=ntp state=installed

  - name: Start and enable NTP
    service: name=ntpd  state=started  enabled=yes

  - name: Install nginx
    yum: name=nginx state=installed
    
  - name: Start & Enable nginx
    service: name=nginx state=started enabled=yes

  - name: Add default page
    template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
    when: inventory_hostname != 'hp'
    notify: Restart nginx
    
