---

 - name: Install MariaDB
   yum:
    state: installed
    name:
      - mariadb-server
      - MySQL-python

 - name: Add MySQL conf
   template: src=my.cnf.j2 dest=/root/.my.cnf
   

 - name: Copy file from /root/.my.cnf to /etc/
   command: cp /root/.my.cnf /etc/my.cnf

 - name: Start MariaDB Service
   service: name=mariadb state=started enabled=yes

 - name: Create MariaDB log file
   file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

 - name: Create database
   mysql_db: name={{ wp_db_name }} state=present

 - name: Create database user
   mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='%' state=present
  
 - name: Start MariaDB Service
   service: name=mariadb state=started enabled=yes

